### ISSUE TITLE
What is the new rating for B?

### ISSUE THREAD

**Issue by Josema** [KenanY/glicko2-lite#154]
This example is very straightforward, but I don't know how to get the new rating of B player. It has won, so must be higher than 2000. And what about if is a draw?

```js
const glicko2 = require('glicko2-lite');

// player A: 1500 rating, 350 rating deviation, and 0.06 volatility
// player B: 2000 rating, 70 rating deviation
// A loses to B
// new rating, rating deviation, and volatility:
glicko2(1500, 350, 0.06, [[2000, 70, 0]])
// => {
// =>   rating: 1467.5878493169462,
// =>   rd: 318.6617548537152,
// =>   vol: 0.059999457650202655
// => }
```

**Comment by Josema** [comment]
I see, I have to run it again in the opposite direcction.

```js
glicko2(2000, 70, 0.06, [[1500, 350, 1]])
```

And for draws the last parameter must be 0.5.

**Comment by DOSFOKDSFOK** [comment]
> Я вижу, я должен запустить его снова в противоположном направлении.
> 
> ```js
> glicko2(2000, 70, 0.06, [[1500, 350, 1]])
> ```
> 
> А для розыгрыша последний параметр должен быть 0,5.

HELP ME WITH COINFY
