### ISSUE TITLE
Return type naming convention

### ISSUE THREAD

**Issue by ddugovic** [KenanY/glicko2-lite#5]
I'm developing a chess server; however, my `player.rating` object has attributes `(r, rd, vol)` rather than `(rating, rd, vol)`.  It would reduce potential ambiguity if this library followed Glickman's [naming convention](http://www.glicko.net/glicko/glicko2.pdf) by returning `r` rather than `rating`.

> Every player in the Glicko-2 system has a rating r, a rating deviation RD, and a rating
volatility σ.

**Comment by KenanY** [comment]
I guess I intended the current name to _reduce_ ambiguity by not shortening it to a single letter. I take it that for your case it would be non-trivial to simply rename the returned attribute to `r`? Nevertheless I think I'm open to this change if it is desired; no harm done so long as I bump the major version.

btw, love your work on adding variants to stockfish :)

**Comment by ddugovic** [comment]
Ah, you are correct, I figured out how in JavaScript to map the returned attributes.

And thanks, I'm glad others have helped me with that effort.
